### ISSUE TITLE
WP_DEBUG turn on?

### ISSUE THREAD

**Issue by StevenTCramer** [iolevel/wpdotnet-sdk#10]
If using the NugetPackage how could we turn on the WP_DEBUG?

**Comment by jakubmisek** [comment]
That's a good point. WP_DEBUG is hardcoded in the release build, but it can be customized in a future version.

Currently the only way of enabling WP_DEBUG is to compile from sources and change it in `wp-config.php`

**Comment by StevenTCramer** [comment]
OK,  This is looking promising.  WordPress has a huge user base and this gives dotnet devs a bigger marketplace.  Thanks for the work.
