### ISSUE TITLE
[Feature] Hot reload in PHP projects

### ISSUE THREAD

**Issue by robertsundstrom** [iolevel/wpdotnet-sdk#101]
To speed up the development cycle, the PHP project should be separately and incrementally compiled and then reloaded once a source file has changed. It is ideal in cases where you work on themes.

I don't know if this is already supported today.  This should probably be filed in the compiler repo.

**Comment by jakubmisek** [comment]
It's actually my current plan - files in wp-content will be compiled upon change - this basically allows the hot reload, and allows for much simpler use.

The compiler provides an API for that already, wpdotnet will just utilize it correctly. So 👍

**Comment by jakubmisek** [comment]
same as https://github.com/iolevel/wpdotnet-sdk/issues/88
