### ISSUE TITLE
Configuring To Subfolder Gives Error Page - Too Many Redirects

### ISSUE THREAD

**Issue by jwbats** [iolevel/wpdotnet-sdk#106]
When configuring WpDotNet to run in a subfolder, the subfolder can't be visited. It errors with a 'too many redirects' error.

How to reproduce:

```
public void ConfigureServices(IServiceCollection services)
{
	services.AddWordPress(options =>
	{
		options.SiteUrl = "https://localhost:44376/blog";
		options.HomeUrl = "https://localhost:44376/blog";
	});
}

// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
	}

	app.UseWordPress();

	app.UseRouting();

	app.UseEndpoints(endpoints =>
	{
		endpoints.MapGet("/", async context =>
		{
			await context.Response.WriteAsync("Hello World!");
		});
	});
}
```

This is a new sandbox app that I'm testing it in. I wanted to know WpDotNet would seamlessly integrate with an existing app that uses endpoint mapping.

Maybe it only works with UseStaticFiles()?

But I'm not interested in just that. The real app that I want to use it in, uses UseStaticFiles() as well as MapControllers() for its endpoints. I can't be expected to rewrite it in order to integrate a new feature.

**Comment by jakubmisek** [comment]
fixed with #114
