### ISSUE TITLE
Jetpack install issue on WPDotNet latest

### ISSUE THREAD

**Issue by Aaronontheweb** [iolevel/wpdotnet-sdk#115]
**Describe the bug**

[Jetpack](https://github.com/Automattic/jetpack) does not appear to be able to start after installation:

```
this document to set up your development environment. Jetpack must have Composer dependencies installed and built via the build command.', 'jetpack' ), array( 'a' => array( 'href' => array(), 'target' => array(), 'rel' => array(), ), ) ), 'https://github.com/Automattic/jetpack/blob/master/docs/development-environment.md#building-your-project' ); ?>
```

**To Reproduce**
Using the latest here: https://github.com/iolevel/peachpie-wordpress/commit/fd4d90779b09d18b75f17e7fb2faa2a476e0c0e5

Install JetPack via the WordPress install dialog 

**Expected behavior**
A successful JetPack installation with no build errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/326939/133149376-d56a1922-ea84-44a5-8e24-5fac841b5a43.png)

**Stack trace:**
If you ran into an exception, please post the stack trace.

**Additional context**
Happens also using the latest versions of PHPie - 

```
<PropertyGroup>
        <WpDotNetVersion>5.8.0-preview10</WpDotNetVersion>
        <PeachpieVersion>1.0.6</PeachpieVersion>
    </PropertyGroup>
```

And

```
<Project>

    <!-- $(PeachpieVersion) property from the current Peachpie.NET.Sdk -->
    <Import Project="Version.props" Sdk="Peachpie.NET.Sdk" Condition=" '$(PeachpieVersion)'=='' " />

    <!-- global properties -->
    <PropertyGroup>
        <WpDotNetVersion>5.7.1-preview7</WpDotNetVersion>
    </PropertyGroup>
</Project>
```

**Comment by jakubmisek** [comment]
Hi @Aaronontheweb! thank you for the details, we'll take a look.

**Comment by jakubmisek** [comment]
@TomatorCZ :)

**Comment by TomatorCZ** [comment]
Hi @Aaronontheweb. It seems to be something wrong with the installation via the dialog. The manual installation (see [docs](https://docs.peachpie.io/scenarios/wordpress/build-php-plugin/)) should work. I will write back after the fix.

**Comment by Aaronontheweb** [comment]
Thank you!

**Comment by jakubmisek** [comment]
thank you for reporting the issue! we'll be releasing the update on NuGet soon
