### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by YordanYanakiev** [iolevel/wpdotnet-sdk#122]
**Describe the bug**
I have a private server, which is running behind a router.
I have redirected port 80 and 443 to the server.
The server is Windows Server 2022 with IIS on it.
I have Visual Studio installed on it, and if I run the application ( a sample app with the WP on it ) - it working fine on localhost.
Once I publish it and place it on the IIS, and try to access it via the domain name - i get only blank page.
Seems like it is triggering the things, since if i put other db connection setting - it result an error message that cant connect to the database, but that's all. Once I return the proper settings - only blank page.

**To Reproduce**
Steps in the main bug description.

**Expected behavior**
To be working..

**System information:**
 - OS: Windows Server 2022 Standard
 - Version 21H2

**Comment by hez2010** [comment]
You need to use the version `5.9.0-rc-001`.

**Comment by YordanYanakiev** [comment]
But.. I am using just it..
![image](https://user-images.githubusercontent.com/6534199/162374118-b0fb05c8-0cbc-40d9-a354-632d34426f74.png)

**Comment by jakubmisek** [comment]
There is probably a runtime exception resulting in the blank page. Please try enabling log in `web.config` to see more details. Something like:

![image](https://user-images.githubusercontent.com/842150/162479328-e317bfab-effd-444b-827b-00b990333d8f.png)

- [ ] Although; we have just noticed, that some fatal exceptions aren't shown either in the log or on the page.

**Comment by YordanYanakiev** [comment]
Tried it, but .. Nope. No log is generated. :|

**Comment by jakubmisek** [comment]
thanks, 

the request handler rethrows exceptions here: https://github.com/peachpiecompiler/peachpie/blob/8041b35b51c2a0b798b5aac4ae73735379fe7b3a/src/Peachpie.AspNetCore.Web/PhpHandlerMiddleware.cs#L398

but it seems it's not displayed by the asp.net core request handler (added here https://github.com/iolevel/wpdotnet-sdk/blob/90bdc0b843db3629560b534cad5e34246bb492ac/app/Program.cs#L44)

I'll try it and eventually add some debug outputs;

**Comment by YordanYanakiev** [comment]
Any development on this, or it is a hard stuff ?

**Comment by jakubmisek** [comment]
Hi @YordanYanakiev - thank you for reminding me. We're just preparing an update that provides you with more details, instead of a blank page.

**Comment by YordanYanakiev** [comment]
Sorry for pushing.  I didn't mean it if it looks as such..

**Comment by jakubmisek** [comment]
absolutely no problem, the blank page is really an annoying issue and we'd totally forget to update it.

**Comment by jakubmisek** [comment]
There's a new release ([5.9.3-rc-002](https://www.nuget.org/packages/Peachpied.WordPress.aspnetcore)) which should at least not show a blank page.

Please let me know if it helps! Thank you

**Comment by YordanYanakiev** [comment]
After compiling with .NET 6.0 - because this is the minimum requirements now seems like - i got this screen.
![image](https://user-images.githubusercontent.com/6534199/163762630-c1f21a08-228f-48e1-a5c2-18b00da62e86.png)
Then I decided that I lack some hosting bundle, and i've stalled .NET 3.1, but not working, then .NET 5.0, but not working, and then .NET 7.0, but again not working. 
![image](https://user-images.githubusercontent.com/6534199/163762713-5ff85340-0e6c-41ab-b6dc-ed3740553177.png)
Not sure what to do next..

**Comment by hez2010** [comment]
You need to restart IIS services or your system after installing .NET windows server hosting bundles

**Comment by YordanYanakiev** [comment]
Well.. I believed the same, so I've restarted the whole server multiple times to be sure. Just as You wrote this I've restarted it again to be sure. No change.

**Comment by hez2010** [comment]
How about uninstalling all .NET sdks/runtimes and server hosting bundles, then restarting the system and reinstalling .NET 6.0 x64 runtime and server hosting bundle only?

**Comment by YordanYanakiev** [comment]
Sec..

**Comment by YordanYanakiev** [comment]
Uninstalled all possible .NET packages. Only the .NET 6.0.300-preview remained since it's part from Visual Studio 2022.
Restarted.
Installed fresh .NET 6
Restarted.
Updated Visual Studio 2022 preview to the latest.
Restarted.
Still the same.
![image](https://user-images.githubusercontent.com/6534199/163768260-cfdd0c81-0e85-49db-be8c-bb06cf6c9a55.png)

**Comment by YordanYanakiev** [comment]
![image](https://user-images.githubusercontent.com/6534199/163768922-c7d94379-6220-4739-bd31-31d2cb240f12.png)
Although - this is what the net info showing.

**Comment by YordanYanakiev** [comment]
[HomeWordpress.deps.json.txt](https://github.com/iolevel/wpdotnet-sdk/files/8504243/HomeWordpress.deps.json.txt)
here my result deps.json ( had to add the .txt extension for github limitation ) if this helps.

**Comment by jakubmisek** [comment]
You can still run it on `netcoreapp3.1`, `net5.0`, `net6.0` .

Anyways; have you tried
```
dotnet publish
```
and run it from the publish folder?

**Comment by YordanYanakiev** [comment]
here:
![image](https://user-images.githubusercontent.com/6534199/163822851-69e6d217-0091-405d-975e-95edc1242d6a.png)

**Comment by YordanYanakiev** [comment]
![image](https://user-images.githubusercontent.com/6534199/163829614-4333f94f-db26-47cd-be6a-255b5dc60186.png)

**Comment by hez2010** [comment]
Are you using `dotnet build` for deployment before?
To deploy it to IIS, you shouldn't use `dotnet build`.
Instead you should use `dotnet publish -c Release` and then deploy the content in `bin\Releaee\net6.0\publish` (`bin\Releaee\net6.0-windows\publish` in your case)

**Comment by YordanYanakiev** [comment]
emh.. i am using VS Pro and VS Enterprise - they have "publish in folder". This goes for all .NET project I am using up to now. I dont use console stuff at all.

**Comment by YordanYanakiev** [comment]
A bit of update:
Went to another dev computer with VS 2019 Enterprise.
Set a new ASP .NET Core Web Application project, added the package, and compiled and published to a folder, then placed the result to the server, and the error remains the same.

**Comment by YordanYanakiev** [comment]
What is your server configuration you are running it ? Something specific ?

**Comment by jakubmisek** [comment]
I would just note this is a general .NET issue - it is not much related to WordPress nor WpDotNet.

So maybe they would help better at stackoverflow, e.g. https://stackoverflow.com/questions/65317970/http-error-500-31-failed-to-load-asp-net-core-runtime - does this help with the issue?

**Comment by YordanYanakiev** [comment]
no. already tried all of noted topics in all possible stackoverflows i could find across the topic, including all in this article.
it feels like it is dependend on a very specific package.

**Comment by YordanYanakiev** [comment]
All possible other subdomains working with compiled there projects on .NET 6.0.
If I run a new .net core app - it works, but in the moment I add this package - the result stop working .

**Comment by YordanYanakiev** [comment]
Thank You guys for everything so far ! :)

**Comment by YordanYanakiev** [comment]
Not sure. It gone with the new version seems like by some reason, and started showing this 500.31.
The project with the old template wasnt modified at all, and it kept showing this error until I decided to go for the new template.
Still not understanding what's the difference between the templates, or there is something left in the old template ?!.. Not sure.

**Comment by jakubmisek** [comment]
Thank you.

I'm closing this issue in favor of https://github.com/iolevel/wpdotnet-sdk/issues/123
