### ISSUE TITLE
Server crashing after opening a couple of articles

### ISSUE THREAD

**Issue by YordanYanakiev** [iolevel/wpdotnet-sdk#123]
**Describe the bug**
Server practically crashing as resulting "error 500" If I open an article and navigate back and forth on it.

**To Reproduce**
Just open an article. Press Back button, then open it again and then press link to go to the main page.

**Expected behavior**
It should not crashing.

**System information:**
 - OS: Server side : Windows Server 2022 Std.

**Stack trace:**
Not available.

**Additional context**
N/A

**Comment by jakubmisek** [comment]
Thank you for reporting the issue;

Do you have anything in the log file? There should be the exception name.

**Comment by YordanYanakiev** [comment]
Not sure where do I look for such file.

**Comment by YordanYanakiev** [comment]
Great ! waiting for it then. :)

**Comment by YordanYanakiev** [comment]
Will be coming the fix soon ?

**Comment by jakubmisek** [comment]
Thanks for reminding me!

The release `5.9.3-rc-003` will be there in a few minutes.

**Comment by YordanYanakiev** [comment]
Fixed ! Thank You very much !! :)
