### ISSUE TITLE
Is there Support for Multi-Domain?

### ISSUE THREAD

**Issue by asparatu** [iolevel/wpdotnet-sdk#130]
I find this project very interesting. The IT company I work at uses WordPress a lot when making new static sites. I want to know if there is an option to set up the installation as a multi-domain install.

**Comment by asparatu** [comment]
I found the information at https://github.com/iolevel/wpdotnet-sdk/blob/master/docs/configuration.md.

**Comment by jakubmisek** [comment]
> I found the information at https://github.com/iolevel/wpdotnet-sdk/blob/master/docs/configuration.md.

thanks for the update :) yep, it's there, but we don't use multisite personally, so it's not battle-tested
