### ISSUE TITLE
PeachPie wordpress can't install theme or plugin

### ISSUE THREAD

**Issue by anilkumarvs** [iolevel/wpdotnet-sdk#131]
Hi,
I have integrated peachpie into my exising .Net 6 web application using the PeachPied.WordPress.AspNetCore version 6.0.1-rc-011. And to load both my existing website and wordpress, I have used conditional mapping and incorporated the worpress inside a subfolder called "/WP". eg http://domain.com/wp/

Code used;
```c#
builder.Services.AddWordPress(options =>
{
    options.HomeUrl =
    options.SiteUrl =  "https://domain.com/wp"; 
});

app.MapWhen(context => context.Request.Path.StartsWithSegments("/wp"), appBuilder =>
{
    appBuilder.UseWordPress();
});
```

All working fine including wp-admin, but when trying to install a theme or plugin, it is always failing. Error like "could not copy files.." or "Stlesheet minning.." etc coming. I have added 755 permission to we-admin, wp-content and wp-include folders. But still not working. Can anyone please help me with this. I have tried re-integrating peachpie different times. But no luck. Is the issue related to the mapping I used? Please help.

**Comment by jakubmisek** [comment]
Hello @anilkumarvs ,

Thank you for your issue;

Please take a look on https://docs.peachpie.io/scenarios/wordpress/build-php-theme/ , specifically the demo app at https://github.com/iolevel/peachpie-wordpress 

It's always best to copy the theme/plugins like this, in a separate project.

**Comment by anilkumarvs** [comment]
Hi Jakub,

Thanks for the reply. I was referring about adding standard themes and plugins from wordpress theme library. 

My issue is, when adding the standard theme, for example Twenty-Twenty-One, it is not successfully installing. Error occurs like stylesheet missing, or could not copy files. 

Is this related to any issue in my peachpie installation? Or is it not possible  to install standard themes/plugins from market.

Your help would be much appreciated.

**Comment by jakubmisek** [comment]
Yes, themes need to be added as described on https://docs.peachpie.io/scenarios/wordpress/build-php-theme/ - not through the dashboard.

Adding through the dashboard is supported, but essentially it's not working efficiently, and might be buggy.

**Comment by anilkumarvs** [comment]
Hi Jakub,

Thanks for the reply. I will use the method described in the link to add new themes.
