### ISSUE TITLE
[How good is it to use wordpress as subfolder?]

### ISSUE THREAD

**Issue by AbdurrahmanSefer** [iolevel/wpdotnet-sdk#139]
have a nice day ;

I want to set up a wordpress site as a subfolder, but I want to ask is it a problem for hosting and server and what are the disadvantages

**Comment by jakubmisek** [comment]
Hello,

There are no known disadvantages. The recommended way is to set `SiteUrl` and `HomeUrl` (https://github.com/iolevel/wpdotnet-sdk#appsettingsjson) to the URL including with your subfolder.
