### ISSUE TITLE
"Error establishing a database connection" after deploying app to Azure App Service

### ISSUE THREAD

**Issue by DeanLaw14** [iolevel/wpdotnet-sdk#140]
Hi, I've been trying to spin up a wordpress site having followed the instructions [here](https://docs.peachpie.io/scenarios/wordpress/aspnetcore-wordpress/). It all works great locally but the issues occur when attempting to access the site after publishing to Azure
![image](https://github.com/iolevel/wpdotnet-sdk/assets/40341387/f0bc2c57-86f9-4d89-b4f8-9d20f04f817c)

I've configured the app as follows:

Wordpress Dotnet application is published to Azure App Service (windows Vm) with these appsettings
![image](https://github.com/iolevel/wpdotnet-sdk/assets/40341387/3cd5d823-d109-4603-a8c3-a10d1789fa36)

Followed [these instructions](https://learn.microsoft.com/en-us/azure/mysql/flexible-server/quickstart-create-server-portal) to create/config the MySql db required
![image](https://github.com/iolevel/wpdotnet-sdk/assets/40341387/3c9b28c1-32e7-4260-aef2-2e2ce06f6d4b)

Hopefully its something obvious that I've missed but any help would be very much appreciated!

**Comment by jakubmisek** [comment]
Hi, glad you're trying WordPress on .NET!

To configure db connection, please follow the instructions at https://docs.peachpie.io/scenarios/wordpress/configuration/#default-configuration

**Comment by DeanLaw14** [comment]
Thanks I wasn't expecting such a swift reply, but after the enabling "MySQL in App" the server isnt being detected
![image](https://github.com/iolevel/wpdotnet-sdk/assets/40341387/f93215f6-1a13-4014-bc7a-2c726f468898)
![image](https://github.com/iolevel/wpdotnet-sdk/assets/40341387/e0620f2e-3cdc-4e25-bb2b-18ede188b182)

Also does this mean that when in production the config options in the `Program.cs` are ignored and the `MYSQLCONNSTR_localdb` ENV variable is used instead?

![image](https://github.com/iolevel/wpdotnet-sdk/assets/40341387/ebae7a95-b6f4-4b48-8acf-c3ef901da14c)

**Comment by jakubmisek** [comment]
If `options.DbHost` is not specified (empty or "localhost"), the Sdk tries to use the `MYSQLCONNSTR_localdb` environment variable and parse the connection information from it. Otherwise, it respects the `options` you set.

So as it is in your screenshot of `Program.cs`, it should use your `config["..."]` values.

**Comment by DeanLaw14** [comment]
Thanks for your help @jakubmisek - the issue was the [MySQL server instance](https://learn.microsoft.com/en-us/azure/mysql/flexible-server/quickstart-create-server-portal) i set up wasnt configured to allow inbound access to the DB server and subsequently the `wordpress` DB. So once I had done configuring the Azure App Service configs like so worked as expected
![image](https://github.com/iolevel/wpdotnet-sdk/assets/40341387/5ee2bb5f-3f7b-419a-9fb7-d95cdba402bf)

Bit of a PEBKAM moment in the end! :D

**Comment by jakubmisek** [comment]
I'm glad it works now :) thanks for the update, and for closing the issue
