### ISSUE TITLE
Create NuGet package

### ISSUE THREAD

**Issue by ffMathy** [iolevel/wpdotnet-sdk#16]
I can't find the NuGet package for this anywhere on NuGet.org. Can we make one?

**Comment by jakubmisek** [comment]
it is right there https://www.nuget.org/packages/Peachpied.WordPress.AspNetCore/1.0.0-alpha4

we don't list them yet, please see https://github.com/iolevel/wpdotnet-sdk/blob/master/README.MD#how-to-add-wordpress-into-your-aspnet-core-app

**Comment by ffMathy** [comment]
Ah, so we don't list because it's alpha? Makes sense.

Any ETA on an RTM?

**Comment by jakubmisek** [comment]
yep, it is not listed since we wouldn't be able to provide a good support yet.

We already use it on production, expecting a month so we can prepare some documentation and tutorials.

**Comment by ffMathy** [comment]
Really cool!
