### ISSUE TITLE
NullReferenceException when posting a comment

### ISSUE THREAD

**Issue by nukedbit** [iolevel/wpdotnet-sdk#21]
**Describe the bug**
When browsing as anonymous user, trying to post a comment will cause the NullReferenceException,
it works fine if the user is logged in.

**Screenshots**
[https://ibb.co/ZYbTjdT](url)

**System information:**
 - OS: Windows 
 - Version 1809

**Stack trace:**

`NullReferenceException: Object reference not set to an instance of an object.
<Root>wp-includes.comment_php.check_comment(Context <ctx>, PhpValue author, PhpValue email, PhpValue url, PhpValue comment, PhpValue user_ip, PhpValue user_agent, PhpValue comment_type)
<Root>wp-includes.comment_php.wp_allow_comment(Context <ctx>, PhpValue commentdata, PhpValue avoid_die)
<Root>wp-includes.comment_php.wp_new_comment(Context <ctx>, PhpValue commentdata, PhpValue avoid_die)
<Root>wp-includes.comment_php.wp_handle_comment_submission(Context <ctx>, PhpValue comment_data)
<Root>.wp-comments-post_php.<Main>(Context <ctx>, PhpArray <locals>, object this, RuntimeTypeHandle <self>)
<Root>.wp-comments-post_php.<Main>`0(Context <ctx>, PhpArray <locals>, object this, RuntimeTypeHandle <self>)
Pchp.Core.Context+ScriptInfo.Evaluate(Context ctx, PhpArray locals, object this, RuntimeTypeHandle self)
Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script)
Peachpie.AspNetCore.Web.PhpHandlerMiddleware+<>c__DisplayClass7_0.<Invoke>b__0()
System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref Task currentTaskSlot)
PeachPied.WordPress.AspNetCore.Internal.DiagnosticExtensions+Middleware.Invoke(HttpContext context)
Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by jakubmisek** [comment]
thank you Sebastian!

**Comment by jakubmisek** [comment]
runtime does not handle following well, will be fixed

![image](https://user-images.githubusercontent.com/842150/53371681-353f8400-3951-11e9-845b-84f9761edaf8.png)

**Comment by jakubmisek** [comment]
will be fixed in the next update
