### ISSUE TITLE
Intro video link broken

### ISSUE THREAD

**Issue by qzjake** [iolevel/wpdotnet-sdk#24]
** Bug **
There is a mention of an intro video but it is not a link and I am unable to find an intro video anywhere.

**To Reproduce**
http://www.wpdotnet.com/resources/
scroll to FAQ  
expand "1. Before you get started"
click on [Intro Video]

**Expected behavior**
I expect to see an intro video

**Screenshots**
Not required

**System information:**
Chrome

**Stack trace:**
N/A

**Additional context**
No additional information

**Comment by jakubmisek** [comment]
@bfistein :)

**Comment by bfistein** [comment]
Thanks @qzjake! Meant to create that video and somehow this slipped through the UATs :)

**Comment by bfistein** [comment]
Thanks again for reporting this @qzjake. I removed the link placeholder for now, but we will do our best to produce an intro video ASAP in order to explain this a bit better. If anything is unclear, feel free to ask in the [PeachPie Gitter chat](https://gitter.im/iolevel/peachpie).
