### ISSUE TITLE
Curl issue in the WordPress admin dashboard news and events panel

### ISSUE THREAD

**Issue by diddledan** [iolevel/wpdotnet-sdk#25]
**Describe the bug**
The dashboard in a new wpdotnet installation has an error in the news feed section that reads:

```plain
RSS Error: A feed could not be found at
https://wordpress.org/news/feed/. A feed with an invalid mime type may
fall victim to this error, or SimplePie was unable to auto-discover it..
Use force_feed() if you are certain this URL is a real feed.

RSS Error: A feed could not be found at
https://planet.wordpress.org/feed/. A feed with an invalid mime type may
fall victim to this error, or SimplePie was unable to auto-discover it..
Use force_feed() if you are certain this URL is a real feed.
```

This appears to be a problem with Peachpie's CURL module.

**To Reproduce**
Install and setup a new instance of WPdotNet and navigate to `/wp-admin`. The error in on that page at the bottom of the right-hand column.

**Expected behavior**
The events and news should be correctly populated from WordPress.org's RSS feeds.

**Screenshots**
![image](https://user-images.githubusercontent.com/147548/55113284-997f7000-50d6-11e9-8c52-167e4f1d75a6.png)

**System information:**
 - OS: Ubuntu 18.10 and Windows 10
 - Version [e.g. 1.04]: Git Master (WordPress 5.1.1)

**Stack trace:**
N/A

**Additional context**
N/A

**Comment by jakubmisek** [comment]
caused by incorrect cURL header processing (cURL returned headers without name, just values)
