### ISSUE TITLE
Add sqlite support

### ISSUE THREAD

**Issue by RKVitaly** [iolevel/wpdotnet-sdk#3]

**Comment by jakubmisek** [comment]
no description provided

**Comment by bfistein** [comment]
We will answer this on Gitter.

**Comment by jakubmisek** [comment]
If you plugin or an app requires PDO SQlite, add a package reference to `https://www.nuget.org/packages/Peachpie.Library.PDO.sqlite`. Check our demo app on https://github.com/iolevel/peachpie-wordpress, add
```xml
<PackageReference Include="Peachpie.Library.PDO.Sqlite" Version="$(PeachpieVersion)" />
```
into `PeachPied.WordPress.MyPlugin.msbuildproj`
