### ISSUE TITLE
http://wpdotnet.com/ is not working

### ISSUE THREAD

**Issue by gautamkrishnar** [iolevel/wpdotnet-sdk#35]
**Describe the bug**
http://wpdotnet.com/ is not working

**To Reproduce**
Visit http://wpdotnet.com/

**Expected behavior**
Site should be shown

**Additional context**
Please add redirect to www when visiting http://wpdotnet.com/

**Comment by bfistein** [comment]
Thank you @gautamkrishnar, we are aware of this issue, which is caused by a slight misconfiguration of the ASP.NET Core response cache. Will be fixed soon with a new release of WpDotNet.

**Comment by jakubmisek** [comment]
fixed, we have kept some apsnetcore 2.0 DLLs in the folder together with 2.2 ..

**Comment by gautamkrishnar** [comment]
👍
