### ISSUE TITLE
Your website does not work

### ISSUE THREAD

**Issue by martinweihrauch** [iolevel/wpdotnet-sdk#38]
Dear Sir / Madam:
I would need professional support for our software company, but your Contact form is broken on your website.
Best regards
Martin

**Comment by bfistein** [comment]
Is it? I will take a look and fix it. Meanwhile ease do get in touch at info at iolevel dot com. Let us know and we'll take it from there.

**Comment by jakubmisek** [comment]
thank you for the issue! 

> dotnet on Azure was `2.2.210` and we compiled against `2.2.500` .. 

should work fine now - closing
