### ISSUE TITLE
Add SALT parameters to Configuration

### ISSUE THREAD

**Issue by Valks** [iolevel/wpdotnet-sdk#4]
Add parameters for SALT configuration. [wp-config.php](https://codex.wordpress.org/Editing_wp-config.php#Security)

Remove the pre-configured SALT values.

Also it would be wise to throw and error if not set and link to docs explaining how to setup, i.e. in the docs link to [https://api.wordpress.org/secret-key/1.1/salt](https://api.wordpress.org/secret-key/1.1/salt) and explain how to convert to appsettings.Development.json and how to set the values securely in production (link to asp.net docs on configuration [ASP.NET Core 2.1 Configuration).](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1&tabs=basicconfiguration)

**Comment by jakubmisek** [comment]
Reasonable to have SALT in C# configuration. There will be default values in .NET `WordPressConfig` so people can change it. Also we'll add sample config to the sample `app`

**Comment by jakubmisek** [comment]
added, you might delete nuget cache so the new package (PeachPied.WordPress.4.9.6 (the same version)) gets downloaded from myget
