### ISSUE TITLE
'Customify' Theme can't load

### ISSUE THREAD

**Issue by Saadi2020** [iolevel/wpdotnet-sdk#40]
**Describe the bug**
'Customify' Theme can't load. show a blank page.

**System information:**
 - OS: Windows 10 Pro x64
 - MySQL 8.0
last version of WP.NET

before i tested it on online host. but didn't work.

**Comment by jakubmisek** [comment]
what is Customify theme? do you have a reference to it?

**Comment by Saadi1988** [comment]
https://wordpress.org/themes/customify/

**Comment by jakubmisek** [comment]
thanks!

**Comment by jakubmisek** [comment]
Seems the theme works. Blank page suggests it has not been compiled. Please note the package has to be first compiled and deployed as described on https://docs.peachpie.io/scenarios/wordpress/build-php-theme/

**Comment by jakubmisek** [comment]
this will be properly fixed/enhanced with https://github.com/iolevel/wpdotnet-sdk/issues/101
