### ISSUE TITLE
'WP-Persian' plugin doesn't work and shows error

### ISSUE THREAD

**Issue by Saadi2020** [iolevel/wpdotnet-sdk#41]
**Describe the bug**
'WP-Persian'  is a plugin to convert gregorian calendar to Persian calendar. but when install show error and not work in the blog pages.

i tested it on my PC and on smarterasp.net host. i use MySQL 8.0.

**Comment by jakubmisek** [comment]
Thank you for reporting the issue. Please provide steps to reproduce, a screenshot and a description and text of the error.

**Comment by Saadi1988** [comment]
![p1](https://user-images.githubusercontent.com/42292489/65957993-2676fd80-e45b-11e9-8cae-ca538c5b6c6a.png)
![p2](https://user-images.githubusercontent.com/42292489/65957994-270f9400-e45b-11e9-8fe9-bf9d56e5a85d.png)
error: This extension built 972 unexpected characters during the activating process. If you receive a "headers already sent" warning message, problems with link feed, or other issues, disable or remove this extension.

**Comment by Saadi1988** [comment]
After, before every page load temporary shows "load();" .Also when i go to add widgets, there is not any Solar Calendar Archive   "بایگانی شمسی".
![p3](https://user-images.githubusercontent.com/42292489/65958383-1e6b8d80-e45c-11e9-8ad9-6db7536a0a6b.png)

**Comment by Saadi1988** [comment]
And there is a new related bug. When i go to "http://localhost:5004/wp-admin/plugin-editor.php" wordpress.net shows error:
"Files with these properties cannot be edited."
plugin is enabled or disabled, wp shows this error.
![p4](https://user-images.githubusercontent.com/42292489/65960156-ac497780-e460-11e9-9f54-d6ce8b4d5018.png)

**Comment by Saadi1988** [comment]
sorry, my database is under MySQL v5. but the main MySQL installed application is v8 Windows 10 Pro.

**Comment by Saadi1988** [comment]
Can you release the newly released bug version of wpdotnet to i test it? thanks.

**Comment by jakubmisek** [comment]
this is probably caused by the plugin not being compiled, or compiled with issues. We'll fix the similar issues properly with https://github.com/iolevel/wpdotnet-sdk/issues/101
