### ISSUE TITLE
Elementor is not working

### ISSUE THREAD

**Issue by LORDofDOOM** [iolevel/wpdotnet-sdk#46]
**Describe the bug**
Cant save in Elementor -> Throw TypeError, it's also not possible to drag anything else than "inner Section" - So it's not possible to drag e.g. images to a section

**To Reproduce**
Install elementor plugin, create a new page and try to save (ignore thats currently directly compiled, same behavior if I create a peachpie plugin for elementor)

**Expected behavior**
Save Content

**Stack trace:**
```
TypeError in D:\peachpie\wordpress\wp-content\plugins\elementor\includes\base\controls-stack.php(1022,3)
Stack trace:
#0 D:\peachpie\wordpress\wp-content\plugins\elementor\includes\base\element-base.php(665,2): Controls_Stack->get_data($item)
#1 D:\peachpie\wordpress\wp-content\plugins\elementor\core\base\document.php(697,3): Element_Base->get_raw_data($with_html_content)
#2 D:\peachpie\wordpress\wp-content\plugins\elementor\core\base\document.php(885,2): Document->get_elements_raw_data($data, $with_html_content)
#3 D:\peachpie\wordpress\wp-content\plugins\elementor\core\base\document.php(540,3): Document->save_elements($elements)
#4 D:\peachpie\wordpress\wp-content\plugins\elementor\core\documents-manager.php(512,2): Document->save($data)
#5 : Documents_Manager->ajax_save($request)
#6 : Module->handle_ajax_request()
#7 : WP_Hook->apply_filters($value, $args)
#8 : WP_Hook->do_action($args)
#9 : do_action($tag, $<arguments>)
#10 : {main}
```

**Comment by bfistein** [comment]
Thank you @LORDofDOOM. Will have a look at this ASAP.

**Comment by jakubmisek** [comment]
@LORDofDOOM thank you for the stack trace, we have been able to fix it with https://github.com/peachpiecompiler/peachpie/commit/c40df775e5fc3a1e7698078fa555d6d79d52a994 (incorrect json decode implementation)

**Comment by davehutton** [comment]
Awesome news! To get this fix do we need to upgrade to the latest / greatest peachpie? I'm not on .net core 3.x yet (2.2) so I didn't know if there was an option for people like me to upgrade without the framework migration

**Comment by jakubmisek** [comment]
@davehutton I'm afraid the asp.net core handler is `netstandard2.1` so `netcoreapp2.2` or higher is required. I would recommend upgrading to 3.x if you can.

**Comment by davehutton** [comment]
ok thanks for your response. Great work on peachpie btw!

**Comment by jakubmisek** [comment]
thank you Dave!
