### ISSUE TITLE
More plugin issues, maybe msbuildproj?

### ISSUE THREAD

**Issue by daniel-arrick** [iolevel/wpdotnet-sdk#49]
I'm wondering if I'm not compiling files right and it is causing some plugins to fail while others work. Sometimes a plugin will work, but other times it won't build or will build but fails to activate and I get uncompiled php displaying in my frontend. Using some advice I got from @LORDofDOOM, I'm simply trying to include all files I need recursively. This seems to work for somethings but plugins are still finicky. Here is my msbuildproj:
`
<Project Sdk="Peachpie.NET.Sdk/0.9.45">
  <Import Project="..\build\Settings.props" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>0e51d101-0992-4aa6-a134-26ea3f2e3934</ProjectGuid>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <VersionPrefix>$(WordPressVersion)</VersionPrefix>
    
    <NoWarn>PHP0125,PHP5011,PHP6002</NoWarn>
    <Copyright>WordPress</Copyright>
    <LangVersion>7.2</LangVersion>
    <Description>WordPress project transformed to managed .NET Standard library.</Description>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**/*.*" Exclude="" />
    <Content Include="**" Exclude="" CopyToOutputDirectory="PreserveNewest">
      <PackagePath>contentFiles/any/netcoreapp3.0/wordpress/</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <Link>wordpress\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
    <Content Include="wp-content/plugins/**/*.php" Exclude="" CopyToOutputDirectory="PreserveNewest">
      <PackagePath>contentFiles/any/netcoreapp3.0/wordpress/</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <Link>wordpress\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
    <Content Include="wp-content/themes/**/*.php" Exclude="" CopyToOutputDirectory="PreserveNewest">
      <PackagePath>contentFiles/any/netcoreapp3.0/wordpress/</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <Link>wordpress\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>
  <ItemGroup>
    
    <ProjectReference Include="..\PeachPied.WordPress.Sdk\PeachPied.WordPress.Sdk.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0-*" PrivateAssets="All"/>
  </ItemGroup>
</Project>`

**Comment by diddledan** [comment]
This is the template I'm using for plugins currently:

```xml
<Project Sdk="Peachpie.NET.Sdk/0.9.46">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>0.1.0-test</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**/*.php" Exclude="**/composer/installers/**;obj/**;bin/**;**/tests/**;**/test/**;**/phpunit/**;**/cli/**;**/composer-php52/**" />
    <Content Include="**" Exclude="obj/**;bin/**;*.msbuildproj" CopyToOutputDirectory="PreserveNewest">
      <PackagePath>contentFiles/any/netcoreapp2.0/wordpress/</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <Link>wordpress\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\peachpied.wordpress\wordpress\PeachPied.WordPress.msbuildproj" />
  </ItemGroup>
</Project>
```

**Comment by daniel-arrick** [comment]
Thank you @diddledan I think this has solved some compilation issues though I frequently get plugin build errors due to problems like _P4044: Type name 'GuzzleHttp\Event\SubscriberInterface' could not be resolved_. Maybe this is a separate dependency problem

**Comment by daniel-arrick** [comment]
I've also found that some plugins put links in their headers with <> tags and those will break compilation.
