### ISSUE TITLE
PeachPied.WordPress project fails to load

### ISSUE THREAD

**Issue by genifycom** [iolevel/wpdotnet-sdk#5]
Using Visual Studio 15.7.5 and opening the .sln files gives

wpdotnet-sdk-master\wordpress\PeachPied.WordPress.msbuildproj : error  : Project file is incomplete. Expected imports are missing.

and the project does not load.

**Comment by jakubmisek** [comment]
this is a known issue when opening in Visual Studio (not VSCode).

Run `dotnet restore` on a commandline before opening in VS 2017.
