### ISSUE TITLE
Email support

### ISSUE THREAD

**Issue by daniel-arrick** [iolevel/wpdotnet-sdk#51]
I was wondering if anyone has gotten outgoing emailing working on their installation? I am having trouble using php mail() and many smtp plugins I try fail to compile or don't work.

Thank you

**Comment by jakubmisek** [comment]
as I know, PHP's `mail` is only capable of unsecured plain text SMTP connection? What plugin have you tried? we may take a look on that :)

**Comment by daniel-arrick** [comment]
One of the only smtp plugins I have compiled successfully is called **Free & Simple Contact Form Plugin - Pirateforms** but didn't send with gmail or pepipost smtp.
Popular ones like **MailPoet** or 
**WP Mail SMTP by WPForms** did not compile and **WP Mail SMTP Plugin by Mail Bank** broke on activation.

**Comment by daniel-arrick** [comment]
I added some code
