### ISSUE TITLE
No plugins available 

### ISSUE THREAD

**Issue by daniel-arrick** [iolevel/wpdotnet-sdk#58]
Hello, I was having some problems compiling plugins while using PeachPie v 0.9.45 so I wanted to try a fresh clone of the repo using the 0.9.600 compiler to see if would solve my issues. But after adding plugins they do not appear in the dashboard at all.
![Screen Shot 2019-11-18 at 10 14 22 AM](https://user-images.githubusercontent.com/46567272/69064872-d218e480-09ec-11ea-9425-d45ca4276841.png)
![Screen Shot 2019-11-18 at 10 20 52 AM](https://user-images.githubusercontent.com/46567272/69065081-21f7ab80-09ed-11ea-8a9f-a0f67dd379af.png)

**Comment by jakubmisek** [comment]
maybe `netcoreapp2.0` in the project file (the first screen) has to be changed to `netcoreapp3.0`?

**Comment by jakubmisek** [comment]
build process seems to be configured incorrectly - excluding all the plugins from the compilation.
