### ISSUE TITLE
InvalidOperationException while trying to register a widget

### ISSUE THREAD

**Issue by medvedy** [iolevel/wpdotnet-sdk#59]
**Describe the bug**
I'm trying to build my own wordpress widget, but I have a problem with registering the widget. I get the following error: "InvalidOperationException: Call to a member function register() on a non-object". 

The exception is thrown in widgets.php, in function "register_widget( $widget )" when executing "$wp_widget_factory->register( $widget );". $wp_widget_factory seems to be null. 

It seems, that $GLOBALS['wp_widget_factory'] = new WP_Widget_Factory(); is executed after the plugin registering. That's why the wp_widget_factory is still null when I try to register my plugin.

This is my plugin/widget: https://github.com/medvedy/wpwidgetdemo/blob/master/DemoWidget.cs 

**To Reproduce**
- Add the plugin to the project
- Provide it with IWpPluginProvider

**Expected behavior**
No exception

**System information:**
- Windows 10, build 18362
- wpdotnet-sdk from 23.11.2019 

**Stack trace:**
Error: Call to a member function register() on a non-object in C:\wpdotnet\wpdotnet-sdk\wordpress\wp-includes\widgets.php(116,0)
Stack trace:
#0 C:\wpdotnet\wpdotnet-sdk\app\Plugins\DemoWidget.cs(13,12): register_widget($widget)
#1 C:\wpdotnet\wpdotnet-sdk\app\Plugins\DemoWidget.cs(21,12): DemoWidgetPlugin->RegisterMyWidget()
#2 C:\wpdotnet\wpdotnet-sdk\PeachPied.WordPress.Sdk\WpLoader.cs(37,16): DemoWidgetPlugin->Configure($app)
#3 C:\wpdotnet\wpdotnet-sdk\wordpress\wp-content\mu-plugins\peachpie-api.php(30,2): WpLoader->AppStarted($app)
#4 C:\wpdotnet\wpdotnet-sdk\wordpress\wp-settings.php(291,1): {main}
#5 C:\wpdotnet\wpdotnet-sdk\wordpress\wp-config.php(89,0): {main}
#6 C:\wpdotnet\wpdotnet-sdk\wordpress\wp-load.php(37,1): {main}
#7 C:\wpdotnet\wpdotnet-sdk\wordpress\wp-admin\admin.php(34,0): {main}
#8 C:\wpdotnet\wpdotnet-sdk\wordpress\wp-admin\index.php(10,0): {main}
#9 : {main}

**Comment by medvedy** [comment]
Problem was: "add_action" should get a reference to a method, but I executed the method instead:

`app.Context.Call("add_action", (PhpValue)"widgets_init", RegisterMyWidget());`

This worked:

```
public delegate int Del();

public int RegisterMyWidget()
{
    var tinfo = PhpTypeInfoExtension.GetPhpTypeInfo<DemoWidget>();
    this.app.Context.DeclareType(tinfo, "DemoWidget");
    this.app.Context.Call("register_widget", "DemoWidget");
    return 0;
}

public void Configure(WpApp app)
{
    this.app = app;
    Del MyDel = RegisterMyWidget;
    var routineInfo = RoutineInfo.CreateUserRoutine("RegisterMyWidget", MyDel);
    app.Context.Call("add_action", (PhpValue)"widgets_init", routineInfo);
}
public class DemoWidget : WP_Widget
{
...
```

Thanks @diddledan @jakubmisek @bfistein

**Comment by bfistein** [comment]
Wonderful, thanks @medvedy!
