### ISSUE TITLE
Alot of warnings

### ISSUE THREAD

**Issue by dmcory** [iolevel/wpdotnet-sdk#6]
Hello!

When i build the project appears alot of warnings

![imagen](https://user-images.githubusercontent.com/19848309/44419062-bef43c00-a53f-11e8-81a8-58b93eae8a08.png)

You can obviously run the project, but i don't think if this is okay.

I am runing the .net core version 2.1.400

**Comment by bfistein** [comment]
This is absolutely normal and the expected behavior - some of these warnings aren't even ours, but pertaining to the WordPress source code.
