### ISSUE TITLE
Error: Call to undefined function openssl_cipher_iv_length()

### ISSUE THREAD

**Issue by daniel-arrick** [iolevel/wpdotnet-sdk#62]
I cannot use the openssl extension from my compiled project. Any tips?

thanks

**Comment by jakubmisek** [comment]
openssl extension is still not supported but it's in progress and will be available soon (https://github.com/peachpiecompiler/peachpie/issues/402)

I'll keep you notified :)

**Comment by daniel-arrick** [comment]
Ok thank you!

**Comment by daniel-arrick** [comment]
By the way, do you know of any crypto libraries that are currently supported?

**Comment by jakubmisek** [comment]
currently, all the password and hash functions work, additionally, openssl has been just merged in.

following hash algorithms are supported:
```
crc32
crc32b

md2
md4
md5

sha1
sha256
sha512

fnv132
fnv1a32
fnv164
fnv1a64

BCrypt

Argon2i
Argon2id

aes-256-cbc
aes-192-cbc
aes-128-cbc
aes-256-ecb
aes-192-ecb
aes-128-ecb
des-ecb
des-cbc
des-ede3
des-ede3-cbc

sha384
```

**Comment by daniel-arrick** [comment]
Thanks a lot, great job!

**Comment by jakubmisek** [comment]
thanks @daniel-arrick ! are you trying any specific WordPress plugin?

**Comment by daniel-arrick** [comment]
There were a few.. but mainly I was just trying to use the openssl library for some quick encrypt/decrypt features. I think I will be moving to use an api call instead of php libraries, but thank you for the hard work

**Comment by jakubmisek** [comment]
@daniel-arrick ok, anyways encrypt/decrypt are implemented and fairly well tested :) since peachpie 0.9.900
