### ISSUE TITLE
Type names can't be resolved

### ISSUE THREAD

**Issue by daniel-arrick** [iolevel/wpdotnet-sdk#63]
Hello, I was hoping someone could guide me to solving missing class issues like the ones I have below, thank you!

Plugin: https://wordpress.org/plugins/amazon-s3-and-cloudfront/

wordpress/wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/Aws/Handler/GuzzleV5/GuzzleStream.php(13,31):
error PHP4044: Type name 'DeliciousBrains\WP_Offload_Media\Aws3\GuzzleHttp\Stream\StreamInterface' could not be resolved.

wordpress/wp-content/plugins/amazon-s3-and-cloudfront/vendor/Gcp/google/cloud-core/src/PhpArray.php(31,24):
error PHP4044: Type name 'DeliciousBrains\WP_Offload_Media\Gcp\DrSlump\Protobuf\Codec\PhpArray' could not be resolved.

**Comment by jakubmisek** [comment]
do you have positions of those errors?

**Comment by daniel-arrick** [comment]
Yes, edited above.

**Comment by jakubmisek** [comment]
Thanks. Seems those two classes are simply not declared anywhere in the sources; in the result, the code cannot be compiled (https://docs.peachpie.io/php/diagnostics/#errors).

The two files (GuzzleStream.php and PhpArray.php) would always cause a fatal error so there are usually two options:

- Exclude those files (and anything depending on it) from the compilation.
In the project file `.msbuildproj` add something like this:
```xml
<ItemGroup>
  <Compile Remove="**/GuzzleV5/GuzzleStream.php;cloud-core/src/PhpArray.php" />
</ItemGroup>
```

- Or add the missing php files defining those missing classes

**Comment by daniel-arrick** [comment]
Sorry, just getting back to this project. I'm curious though, how would this work in traditional Wordpress? Would it not have the same dependency issues? I see a composer file in the plugin that looks like it should handle these dependancies

**Comment by jakubmisek** [comment]
WordPress plugins may contain the composer file but it's probably just a left off. WordPress itself does not install the dependencies. They have to be installed first by the publisher of the plugin and packed into the distributed zip file.

Mostly, this error is caused by the developers not including something that is essential but not actually used, so they never find out there's a missing dependency. The compiler needs to know even it won't be used.

**Comment by daniel-arrick** [comment]
Thank you for the solution and the excellent support. Are you accepting donations for your project?

**Comment by bfistein** [comment]
Hi @daniel-arrick, we do, thanks :) either on Paypal (link in the readme of PeachPie's main repo) or on open collective (sponsor button in the PeachPie repo). Thanks for your support!
