### ISSUE TITLE
Fail to run on local IIS

### ISSUE THREAD

**Issue by robertsundstrom** [iolevel/wpdotnet-sdk#66]
I published to a Local IIS using Visual Studio. 

netcore3.1
Self-contained 
win-x64

I cannot even launch the site in a browser when running the resulting .exe manually.
It does not show any response in the console.

It all works when running a pre-publish build launched from Visual Studio.

What am I doing wrong?

.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PeachPied.WordPress.AspNetCore" Version="1.0.0-beta902" />
  </ItemGroup>

</Project>
```

Program.cs:
```csharp
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

using System.IO;

namespace WordpressSite1
{
    class Program
    {
        static void Main(string[] args)
        {
            Directory.SetCurrentDirectory(Path.GetDirectoryName(typeof(Program).Assembly.Location));

            //
            var host = WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseUrls("http://*:5004/")
                .Build();

            host.Run();
        }
    }
}
```
Startup.cs:
```csharp

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace WordpressSite1
{
    class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddResponseCompression();
        }

        public void Configure(IApplicationBuilder app, IHostEnvironment env, IConfiguration configuration)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseWordPress();

            app.UseDefaultFiles();
        }
    }
}
```

Console:
```cmd
❯ .\WordpressSite1.exe                                                                                                  Hosting environment: Production
Content root path: C:\inetpub\wwwroot\Wordpress
Now listening on: http://[::]:5004
Application started. Press Ctrl+C to shut down.
```

**Comment by robertsundstrom** [comment]
When viewing, ```http://localhost:83``` redirects to ```http://localhost:44317/```

**Comment by jakubmisek** [comment]
If WordPress was originally installed on http://localhost:44317/, it automatically redirects you there when requested.

**Comment by robertsundstrom** [comment]
@jakubmisek Ah! I will change it it and see. I just assumed it worked like an ordinary app - ignoring that Wordpress has its own configuration. 🙂

**Comment by jakubmisek** [comment]
maybe we can override this configuration from C# because this is causing troubles to many people! :)

**Comment by robertsundstrom** [comment]
> maybe we can override this configuration from C# because this is causing troubles to many people! :)

Ah, yes. Great idea, but I wonder if that is possible since Wordpress seems to be based upon a hardcoded URL.

https://wordpress.org/support/article/changing-the-site-url/

You could at least add the option to appSettings.json. Letting the user set the URL there for Production. Defaulting to the hosts URL in Development mode. (When the settings is absent)

**Comment by robertsundstrom** [comment]
I wrote an issue #67 for the enhancement.
