### ISSUE TITLE
[Feature] 'siteurl' and 'home' should be set by the host

### ISSUE THREAD

**Issue by robertsundstrom** [iolevel/wpdotnet-sdk#67]
## Description

Wordpress requires you to set the ```siteurl```and ```home``` variables (``wp_options``` in the database) to your requested Site URL:s in order to properly serve the website. 

These are configurable from the admin UI but for development purposes it would be more convenient if it was automatically set to the address of the hosting ASP.NET Core host: ```http://localhost:5000/```, for example.

The ```siteurl``` and ```home``` variables should be configurable/overridable in the ```appsettings.json``` files so that the ```Production``` config can have a fixed url. 

## Configuration

Adding the following options to ```appsettings.json```:

```json
{
  "WordPress": {
    "siteurl": "<your-url>",
    "home": "<your-url>"
  }
}
```

These can be set separately and do not have to be equal.

## Specification
```siteurl``` and ```home``` are NOT set in ```appsettings.json``` and Wordpress uses the URL of the ASP.NET Core host.

```siteurl``` and ```home``` ARE set in ```appsettings.json``` and they override the behavior.

The default behavior of Wordpress is overridden.

## Links
* https://wordpress.org/support/article/changing-the-site-url/

**Comment by robertsundstrom** [comment]
Is it as easy as this?

1. Add the options here:
https://github.com/iolevel/wpdotnet-sdk/blob/fb124e9f8b52bee44bcd23866c5767cef3af3c99/PeachPied.WordPress.AspNetCore/WordPressConfig.cs

2. Set it here (assuming the variables are treated as globals):
https://github.com/iolevel/wpdotnet-sdk/blob/8a316eaeea83766722d762f7cf5fb2258342edf1/PeachPied.WordPress.AspNetCore/RequestDelegateExtension.cs#L165

**Comment by jakubmisek** [comment]
is it sufficient to set a PHP global variable or a PHP constant? I think WordPress stores those values into database

**Comment by robertsundstrom** [comment]
@jakubmisek Yes, they are stored in a database. I have not idea where they are stored when loaded.

Sorry.

**Comment by jakubmisek** [comment]
@robertsundstrom ok let's see what we can do :) also thinking about multisite installation

**Comment by robertsundstrom** [comment]
@jakubmisek Yes, I was thinking about that - "what about multisite?" I have not clue, really. :)

**Comment by jakubmisek** [comment]
seems there is a configuration for that in WordPress
https://wordpress.org/support/article/editing-wp-config-php/#blog-address-url

So we can simply define a constant `WP_HOME` which does the trick - as you suggested in the issue!
