### ISSUE TITLE
can build WP but not WC

### ISSUE THREAD

**Issue by amirvenus** [iolevel/wpdotnet-sdk#68]
**Describe the bug**

I cloned the repo, after updating the nuget packages to the latest versions and editing the configuration file, I managed to build WordPress. 

However, when tried to compile WooCommerce, I got over 2523 warnings and 422 errors even though I removed the 'test' files/folders as well. 

**To Reproduce**

Download the latest WC zip (v4.0) and try to compile it. 

**Expected behavior**

Ideally, it would have to compile well just like WP did. 

**System information:**
 - OS: Windows 10
 
 
**Additional context**

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/5879559/76813541-3bb8cc00-67f0-11ea-8ada-4c1bfc160f6d.png">

I get the following errors when building:

 
Error | MSB3021 | Unable to copy file "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AimeosInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AimeosInstaller.php". Could not find a part of the path 'bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AimeosInstaller.php'. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3027 | Could not copy "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\includes\shipping\legacy-international-delivery\class-wc-shipping-legacy-international-delivery.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\includes\shipping\legacy-international-delivery\class-wc-shipping-legacy-international-delivery.php". Exceeded retry count of 10. Failed. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3021 | Unable to copy file "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\includes\shipping\legacy-international-delivery\class-wc-shipping-legacy-international-delivery.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\includes\shipping\legacy-international-delivery\class-wc-shipping-legacy-international-delivery.php". Could not find a part of the path 'bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\includes\shipping\legacy-international-delivery\class-wc-shipping-legacy-international-delivery.php'. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3027 | Could not copy "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\action-scheduler\classes\data-stores\ActionScheduler_wpPostStore_PostStatusRegistrar.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\action-scheduler\classes\data-stores\ActionScheduler_wpPostStore_PostStatusRegistrar.php". Exceeded retry count of 10. Failed. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3021 | Unable to copy file "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\action-scheduler\classes\data-stores\ActionScheduler_wpPostStore_PostStatusRegistrar.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\action-scheduler\classes\data-stores\ActionScheduler_wpPostStore_PostStatusRegistrar.php". Could not find a part of the path 'bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\action-scheduler\classes\data-stores\ActionScheduler_wpPostStore_PostStatusRegistrar.php'. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3027 | Could not copy "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AimeosInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AimeosInstaller.php". Exceeded retry count of 10. Failed. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3027 | Could not copy "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AnnotateCmsInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AnnotateCmsInstaller.php". Exceeded retry count of 10. Failed. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3021 | Unable to copy file "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AnnotateCmsInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AnnotateCmsInstaller.php". Could not find a part of the path 'bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AnnotateCmsInstaller.php'. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3027 | Could not copy "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AsgardInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AsgardInstaller.php". Exceeded retry count of 10. Failed. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3021 | Unable to copy file "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AsgardInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AsgardInstaller.php". Could not find a part of the path 'bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AsgardInstaller.php'. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3027 | Could not copy "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AttogramInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AttogramInstaller.php". Exceeded retry count of 10. Failed. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3021 | Unable to copy file "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AttogramInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AttogramInstaller.php". Could not find a part of the path 'bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\AttogramInstaller.php'. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3027 | Could not copy "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\BitrixInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\BitrixInstaller.php". Exceeded retry count of 10. Failed. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3021 | Unable to copy file "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\BitrixInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\BitrixInstaller.php". Could not find a part of the path 'bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\BitrixInstaller.php'. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3027 | Could not copy "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\BonefishInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\BonefishInstaller.php". Exceeded retry count of 10. Failed. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3021 | Unable to copy file "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\BonefishInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\BonefishInstaller.php". Could not find a part of the path 'bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\BonefishInstaller.php'. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3027 | Could not copy "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\ClanCatsFrameworkInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\ClanCatsFrameworkInstaller.php". Exceeded retry count of 10. Failed. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3021 | Unable to copy file "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\ClanCatsFrameworkInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\ClanCatsFrameworkInstaller.php". Could not find a part of the path 'bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\ClanCatsFrameworkInstaller.php'. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3027 | Could not copy "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CiviCrmInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CiviCrmInstaller.php". Exceeded retry count of 10. Failed. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3027 | Could not copy "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CakePHPInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CakePHPInstaller.php". Exceeded retry count of 10. Failed. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3021 | Unable to copy file "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CiviCrmInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CiviCrmInstaller.php". Could not find a part of the path 'bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CiviCrmInstaller.php'. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3021 | Unable to copy file "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CakePHPInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CakePHPInstaller.php". Could not find a part of the path 'bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CakePHPInstaller.php'. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3027 | Could not copy "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CockpitInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CockpitInstaller.php". Exceeded retry count of 10. Failed. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |  
Error | MSB3021 | Unable to copy file "C:\Users\Amir H\Downloads\wpdotnet-sdk-master\wpdotnet-sdk-master\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CockpitInstaller.php" to "bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CockpitInstaller.php". Could not find a part of the path 'bin\Debug\netstandard2.1\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-admin\vendor\composer\installers\src\Composer\Installers\CockpitInstaller.php'. | PeachPied.WordPress.AspNetCore | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets | 4570 |

**Comment by amirvenus** [comment]
After making some changes to the proj file:

 <Project Sdk="Peachpie.NET.Sdk/0.9.46"> <Import Project="..\build\Settings.props" /> <PropertyGroup Label="Globals"> <ProjectGuid>0e51d101-0992-4aa6-a134-26ea3f2e3934</ProjectGuid> </PropertyGroup> <PropertyGroup> <TargetFramework>netstandard2.0</TargetFramework> <VersionPrefix>$(WordPressVersion)</VersionPrefix>  <NoWarn>PHP0125,PHP5011,PHP6002</NoWarn> <Copyright>WordPress</Copyright> <Description>WordPress project transformed to managed .NET Standard library.</Description> <LangVersion>7.2</LangVersion> </PropertyGroup> <ItemGroup> <Compile Include="**/*.php" Exclude="wp-config-sample.php;wp-content/uploads/**;wp-content/plugins/hello.php;wp-content/plugins/akismet/**;wp-content/plugins/buddypress/cli/**;wp-content/plugins/woocommerce/packages/**;wp-content/plugins/woocommerce/src/**;wp-content/plugins/woocommerce/vendor/**;wp-content/plugins/woocommerce/includes/legacy/api/*.php;wp-content/plugins/woocommerce/includes/wccom-site/rest-api/endpoints/class-wc-rest-wccom-site-installer-controller.php" /> <Content Include="**;wp-content/plugins/*/*.php" Exclude="**/.git/**;obj/**;bin/**;wp-content/uploads/**;wp-content/plugins/akismet/**;*.msbuildproj" CopyToOutputDirectory="PreserveNewest"> <PackagePath>contentFiles/any/netcoreapp3.0/wordpress/</PackagePath> <PackageCopyToOutput>true</PackageCopyToOutput> <Link>wordpress\%(RecursiveDir)%(Filename)%(Extension)</Link> </Content> </ItemGroup> <ItemGroup>  <ProjectReference Include="..\PeachPied.WordPress.Sdk\PeachPied.WordPress.Sdk.csproj" /> </ItemGroup> <ItemGroup> <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0-*" PrivateAssets="All" /> </ItemGroup> </Project>

I am getting less errors:

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/5879559/76815072-82102a00-67f4-11ea-97ef-8dcc48a7d956.png">

Is it because I deleted the test folders altogether? I don't know how to exclude them otherwise!

**Comment by jakubmisek** [comment]
`MSB3021` is an I/O error (Could not copy ...), no changes to the project files needed. Just restart your Visual Studio and try to build again.

**Comment by jakubmisek** [comment]
In order to remove tests from the compilation, add following to the project file (we'll update it in here with this change soon)

```xml
<ItemGroup>
  <Compile Remove="**\tests\**; />
</ItemGroup>
```

**Comment by jakubmisek** [comment]
btw as of now, woocommerce 3 has been tested, version 4 still has issues

**Comment by amirvenus** [comment]
Following [01a4279](https://github.com/iolevel/wpdotnet-sdk/commit/01a4279024c09404f4667c5c67ccbfea9e308fa2) and applying the changes, I am now getting this error:

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/5879559/76893024-8e8f9380-6883-11ea-8a97-da170dea74f8.png">

**Comment by amirvenus** [comment]
Please find the whole error log:

https://gist.github.com/amirvenus/f0264366040ac2f01143cfa38992ae30

I tried closing VS and opening again but the situation stays the same.

**Comment by jakubmisek** [comment]
the issues above are fixed by extending `"**/tests/**"` from compile items

closing, as woocommerce can be compiled now
