### ISSUE TITLE
i am getting error when using my own theme in place of default twentyseventeen.

### ISSUE THREAD

**Issue by sojinaga** [iolevel/wpdotnet-sdk#7]
I tried with default and it worked. But when using a different theme it failed to start with given error.
`error MSB3073: The command "dotnet compile-php @obj/Debug/netstandard2.0/compile-php-args.rsp" exited with code 134.`

Am i doing it correct or i need to make change at some places for my theme to work?

**Comment by jakubmisek** [comment]
There is an exception in the middle of the output log. Please post the exception with the stack trace.

**Comment by sojinaga** [comment]
I was doing all this on linux. Can you tell me how i can generate the stack
trace?

**Comment by jakubmisek** [comment]
Just see your output that ends with that `error MSB3073 ...`. Scroll up and find the exception.

**Comment by jakubmisek** [comment]
there should be more in the console

**Comment by sojinaga** [comment]
no this is all i got.

**Comment by jakubmisek** [comment]
Please try with the latest update (Peachpie 0.9.9). If will solve all these `NU1603` warnings and probably gets you more information.

**Comment by sojinaga** [comment]
Sure. thanks.

**Comment by jakubmisek** [comment]
if the issue remains, please open a new one in peachpie repo. closing for now
