### ISSUE TITLE
Problem with exec()

### ISSUE THREAD

**Issue by daniel-arrick** [iolevel/wpdotnet-sdk#76]
I'm trying to run shell commands using exec/shell_exec but I get errors like:

/bin/ls: /bin/ls: cannot execute binary file

Some sort of environment configuration I am missing?

Thank you

**Comment by jakubmisek** [comment]
exec/shell_exec is somehow supported, but it may be not tested on Linux and macOs.

What environment and what shell command are you running?

**Comment by daniel-arrick** [comment]
I use MacOS and linux. At first I was trying to use aws cli commands but those failed due to problems with running python scripts from exec(). Then I tried something more rudimentary like "ls" and that failed so it seems like a more general issue with the environment. 
Example response from "ls" command: `/bin/ls: /bin/ls: cannot execute binary file`

**Comment by jakubmisek** [comment]
quick question - how is this issue related to WordPress?

**Comment by daniel-arrick** [comment]
Do you mean what I am trying to accomplish?
What I am trying to accomplish is a way to manage my media content on AWS S3. I cannot find a plugin that is natively supported by the Peachpie compiler mostly due to yielding from try catch finally in the PHP AWS SDK is not supported I believe. That leads me to trying the command line interface and investigating how I can integrate it using hooks ands filters.

**Comment by jakubmisek** [comment]
oh so you are implementing your WordPress plugin?

AFAIK yielding from try catch is easy to workaround:

```php
try
{
  yield $x;
}
```
->
```php
try
{
  $value = $x;
}
yield $value
```

it just have to be done manually, compiler does not have this kind of analysis (yet).

**Comment by daniel-arrick** [comment]
Ok thanks for the tip! I'll have to try that out. 
I missed you added unix shell support in the comment above. Thank you again, I will test it out the new compiler soon

**Comment by daniel-arrick** [comment]
Thank you for releasing the new compiler with unix shell support. 
After lots of trials I found that in order to execute a command with arguments I needed to **surround the entire command with escaped double quotes**.

This works
`shell_exec("ls")`

This fails as the "-l" flag is excluded for some reason
`shell_exec("ls -l")`

This works
`shell_exec("\"ls -l\"")`

**Comment by jakubmisek** [comment]
thanks daniel! great tips, this should be easy to fix for us

**Comment by jakubmisek** [comment]
should be fixed in the latest update :) please let me know if it still fails
