### ISSUE TITLE
Using this project on Azure with SSL configured results in redirect loop.

### ISSUE THREAD

**Issue by assafY** [iolevel/wpdotnet-sdk#77]
When deploying this project in a docker container in an Azure App Service, it works as expected over http. However, after binding a certificate and forcing redirection to https, accessing the admin platform results in the infamous redirect loop.

The solution to this issue when using the PHP version is https://stackoverflow.com/questions/27193575/wordpress-cloudfront-flexible-ssl-ends-up-in-redirect-loop-https/27193576#27193576.

However, to my understanding this is not possible to do in the .NET project.

**Comment by jakubmisek** [comment]
I see! do you know if Azure acting as a proxy sends the same `HTTP_X_FORWARDED_PROTO` header?

**Comment by assafY** [comment]
Amazing. Thank you for the quick response and solution :)

**Comment by jakubmisek** [comment]
thanks for reporting it :)
