### ISSUE TITLE
Failed to update themes due to checksum issue

### ISSUE THREAD

**Issue by hez2010** [iolevel/wpdotnet-sdk#79]
**Describe the bug**
Failed to update themes due to checksum issue

**To Reproduce**
Update themes in wp-admin

**Expected behavior**
Update successfully

**Screenshots**
The checksum appears to be equal to the expected value but it reported mismatch...
![image](https://user-images.githubusercontent.com/14960345/85222625-4dad9a80-b3ef-11ea-97d7-ba3a7e02d432.png)

**System information:**
 - OS: Ubuntu 18.04
 - Version: 1.0.0-beta990

**Comment by jakubmisek** [comment]
It should not even try downloading from downloads.wordpress.org, won't work.

Updates in this way are disabled in WpDotNet.

Have you changed some settings or this is a clean installation?

**Comment by hez2010** [comment]
WpDotNet files are clean installation (I removed all old files and then extracted 0.9.990). 
Database used to create with 0.9.970.

**Comment by jakubmisek** [comment]
So the dashboard suggested you to update themes? They should be up-to-date already.

**Comment by hez2010** [comment]
> So the dashboard suggested you to update themes? They should be up-to-date already.

There're update icon on both the wp-admin navi bar and theme page.
