### ISSUE TITLE
Site wont run .Command execution failed

### ISSUE THREAD

**Issue by SpeedOfSpin** [iolevel/wpdotnet-sdk#8]
Hi

I am running the solution in Visual Studio 2017 and I can't get the site to come up. I have checked I can connect to mySql on docker and all is fine there. When I run the code and browse to the site I just get these errors in the debug window. Any ideas what the problem is?

Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:5004/robots.txt  
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:5004/wp-admin/install.php  
Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware:Information: No cached response available for this request.
PHP (Warning): Command execution failed: Table 'wordpress.wp_options' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_options' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_options' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_options' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_users' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_users' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_usermeta' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_usermeta' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_posts' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_comments' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_posts' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_links' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_comments' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_options' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_links' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_postmeta' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_options' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_terms' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_postmeta' doesn't exist
PHP (Warning): Command execution failed: Table 'wordpress.wp_term_taxonomy' doesn't exist

**Comment by jakubmisek** [comment]
I don't see any error, the wp installation is just slow when debugging because it throws so many warnings.

**Comment by SpeedOfSpin** [comment]
HI there. I tried that and left it over night and still the same.

**Comment by jakubmisek** [comment]
Don't have to leave it over night. It takes about 3-5 seconds.

**Comment by SpeedOfSpin** [comment]
ok but it doesn't work. Are there any other logs I can give you to figure out why it isn't working?

**Comment by jakubmisek** [comment]
First, the MySQL connection is OS, because you are getting all these warnings. WordPress at first installation "tries" to migrate existing tables (which does not exist), and every attempt causes a warning, and every warning slows the debugging by a second.

If you try to start the project with `Ctrl+F5`, you should see the installation form, and the installation should proceed in few seconds.

If you don't, run the project with `F5` (run with debug) and watch Visual Studio's "Output" window ... it will either contain an exception or another useful information, or you will see a typical Visual Studio's Exception dialog.

You can post me the content of the `Output` window in here.

**Comment by SpeedOfSpin** [comment]
I appreciate your help on this. ;-) Really want to get it going.

I have tried running with ctrl-f5 but get the same issue. I have tried running in debug mode and the output above is all I get in the debug window.

When stepping through the PHP code it seems to struggle in this function
is_blog_installed()

when I go through this it goes through a loop of 12 tables checking if they exist or not. Each iteration of the loop gets slower and slower. It uses 90% of my CPU and around 4GB of memory when it finally gets to the last table check. This whole process takes around an hour.

I don't get any exceptions from the c# code.

Thanks
Erik

**Comment by jakubmisek** [comment]
yes, that one tries to upgrade all these non-existing tables.

Next, how does it continue after `is_blog_installed()` ?

**Comment by jakubmisek** [comment]
so this line of code get called?
`wp_redirect( $link );`

**Comment by SpeedOfSpin** [comment]
ok great. BTW, it does hit 
`wp_redirect( $link );`

Thanks again!

**Comment by SpeedOfSpin** [comment]
Just to confirm I checked out an earlier version and I could install WordPress with no problem.

thank you

**Comment by jakubmisek** [comment]
Try updating the project (it now uses prerelease version `0.9.9-CI01218`)

Anyway; If it hits `wp_redirect`, then I guess the request time-outed and you've not been redirected in the browser

**Comment by SpeedOfSpin** [comment]
Still the same sorry. I have gone back one at a time and the last version that worked for me was
[https://github.com/iolevel/wpdotnet-sdk/commit/ad680d35518a7b79c78e60a35c33a265de927640](url)

**Comment by SpeedOfSpin** [comment]
Yep great. That works for me thank you very much. :-)

**Comment by SpeedOfSpin** [comment]
Yep please do.
