### ISSUE TITLE
Page title shows &lsaquo; instead of "<"

### ISSUE THREAD

**Issue by bfistein** [iolevel/wpdotnet-sdk#82]
![image](https://user-images.githubusercontent.com/17054650/93135255-5524cd00-f6da-11ea-9ab1-81084d206081.png)

Running PeachPie 1.0.0-preview1+35c296f6a164ac2862b99aae6588d6c38b39149f

**Comment by jakubmisek** [comment]
fixed in https://github.com/peachpiecompiler/peachpie/commit/43da23d80d5b1a5e0a816eb448dbe758a1f2c892
