### ISSUE TITLE
multisite support

### ISSUE THREAD

**Issue by jakubmisek** [iolevel/wpdotnet-sdk#87]
Currently multisite is not documented/supported.

This feature requires related configuration and to be tested on peachpie.

**Comment by TomatorCZ** [comment]
It is done by [pull request#112](https://github.com/iolevel/wpdotnet-sdk/pull/112).

**Comment by jakubmisek** [comment]
thanks Tomas!

**Comment by tharlab** [comment]
is domain mapping also supported?
https://github.com/wpmudev/domain-mapping
