### ISSUE TITLE
[Feature] Use peachpie to compile php files in theme to make theme includes php work properly.

### ISSUE THREAD

**Issue by mahoshojoHCG** [iolevel/wpdotnet-sdk#88]
**Description**
Some themes contains custom php files. Why not compile them when upload to make them work properly.

**Comment by jakubmisek** [comment]
I agree, wpdotnet may compile any uploaded themes/plugins upon first run.

**Comment by jakubmisek** [comment]
This is related to https://github.com/iolevel/wpdotnet-sdk/issues/101 - we'll track the progress in there.
