### ISSUE TITLE
Many Plugins are not supported

### ISSUE THREAD

**Issue by prashanthganathe** [iolevel/wpdotnet-sdk#89]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.
1. Upload plugins from https://wordpress.org/plugins/dw-question-answer/#reviews
  b. https://wordpress.org/plugins/anspress-question-answer/
2.Elementor

**Expected behavior**
plugin should be activated without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/1222161/94756192-6812ef00-03b4-11eb-9d1d-ef9e2e1597b9.png)

**System information:**
 - Version [e.g. 1.04]

**Stack trace:**
If you ran into an exception, please post the stack trace.

**Additional context**

**Comment by jakubmisek** [comment]
Hi, to install plugins to wpdotnet, follow the steps in https://docs.peachpie.io/scenarios/wordpress/add-plugin-theme/

If you copy plugins as source code, they will be treated as a text.

**Comment by jakubmisek** [comment]
closing, as it is the same as https://github.com/iolevel/wpdotnet-sdk/issues/88
