### ISSUE TITLE
customize links are not working

### ISSUE THREAD

**Issue by armache** [iolevel/wpdotnet-sdk#94]
Whenever a customize link is clicked a blank page is displayed. Sample URL is below:
http://localhost:5004/wp-admin/customize.php?url=http%3A%2F%2Flocalhost%3A5004%2F

**To Reproduce**
Clone a fresh copy, then start the app and click on Customize link

**Expected behavior**
Expecting to see a web page that provides customization functionality.

**Comment by jakubmisek** [comment]
Thank you for reporting the issue. It is being caused by a bug in PeachPie `1.0.0-preview4` runtime (https://github.com/peachpiecompiler/peachpie/issues/887). The next update will be fixed.

**Comment by armache** [comment]
Is the bug fixed? I've restored the project and still having the same issue.

**Comment by jakubmisek** [comment]
@armache It's not happening in wpdotnet 5.6.0-preview5 (at least for me). 

Are you using this repo from sources or the NuGet package `Peachpied.WordPress.AspNetCore`?

**Comment by armache** [comment]
I am using this repo. After cloning the latest code I can confirm that this bug is fixed. Many thanks.

**Comment by jakubmisek** [comment]
thanks for confirmation!
