### ISSUE TITLE
[Feature] Woocommerce

### ISSUE THREAD

**Issue by matiaskusack** [iolevel/wpdotnet-sdk#98]
**Description**
Hi, I'm new to WP and I was hoping to test Woocommerce, but I haven't been able to install it.

I read that plugins must be referenced as Nuget packages as says here: https://docs.peachpie.io/scenarios/wordpress/add-plugin-theme/
But there's no WC there, so I've tried to install it my self by adding WC pluging directly into wordpress/plugins.
It installed, but never activated nor error was shown.

Is there anywhere I can find some info on this or somehow I can debug it?

Thanks in advance. Regards.

**Comment by jakubmisek** [comment]
Hi, we are already running Woocommerce, and successfully, but we haven't published it yet.

This tutorial covers how to add the plugin to WpDotNet https://docs.peachpie.io/scenarios/wordpress/build-php-plugin/

The simplest way is to grab this project https://github.com/iolevel/peachpie-wordpress and copy Woocommerce sources into `MyContent/plugins`, and hit `dotnet run`.

**Comment by matiaskusack** [comment]
Oh! Thank you so mutch. I'll give it a try.

Thanks!
